### ISSUE TITLE
Time Tracking Priorities 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1132]
# Marcello: Activities: Started At / Completed At
- [x] Fix the started at bug to get accurate times.
- [x] The computation for admin dashboard: for all students, calculate the time spent per activity session. 
- [x] If any activity is greater than 30 minutes or less than 1 minute, we set it as 7 minutes. 
- [x] For each teacher let’s calculate a sheet with the following columns: teacher’s name; Most recent timestamp (whatever we can pull, such as when a unit is created); # of activities less than one minute; # of activities between 1 and 5; # of activities 5 and 10; #activities 10 - 30, # of activities greater than 30.

**Comment by marcellosachs** [comment]
For this one - "If any activity is greater than 30 minutes or less than 1 minute, we set it as 7 minutes."
I'm using an estimate (pretty much 7 minutes) gathered from the following query - https://dataclips.heroku.com/tympuxntqzshpmngbnbivaectbqm-average-time-per-activity_session.
