### ISSUE TITLE
Time Tracking in Quill Grammar & Quill Grammar Partner 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1133]
# Donald: In-App Tracking
- [ ] We set up a time counter within the concept results. 
- [ ] With each question, we include a started at and completed at time counter. 
- [ ] The started at should create the stamp each time the question is loaded. (overwrite the old stamp if the page is refreshed). 
- [ ] Each time a student answers a question, we fire the concept result as a segment event to amplitude (Identity the student and pass the data back via Segment). 
- [ ] The data is searchable within the lms results, but we don't do anything with it for now. 
- [ ] We then add the code into the Quill Grammar partner app to track the same data. 

# Problem: 
(passage proofreader - how do we calculate this? for example, time spent reading could be baked in (first concept result is time of page load to answer, 2nd time stamp could be from the end of first question answered to the end of 2nd result, etc). 

# Crunching the Concept Results 
Once we are passing the data back in the concept results, we could also calculate time for teachers and administrators by summing all of the time for all of the students for all of the results. For a classroom of 100 students with 2,000 concept results per student, this is summing the result of 200,000 entries. 
- How long will this take to crunch as JSON data stored within HStore?
- Should we crunch this number as a background job?
- Should we show a spinner while we serve that result?
