### ISSUE TITLE
Teacher Checklist - Do This

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1744]
Everything in here is done except for tutorials. We also need to decide on endpoints for some of the other ones.

# View Tutorials for Each Quill Tool
- [ ] View Quill Overview Tutorial 
- [ ] View Quill Diagnostic Tutorial
- [ ] View Quill Lessons Tutorial
- [ ] View Quill Connect Tutorial

# Assign Activity From Each Tool
- [x] Assign Quill Diagnostic Activity
- [x] Assign Quill Lessons Activity
- [x] Assign Quill Connect Activity
- [x] Assign Quill Proofreader Activity
- [x] Assign Quill Grammar Activity

# Complete Activities With Your Students
- [x] Complete 10 Activities 
- [x] Complete 100 Activities
- [x] Complete 250 Activities
- [x] Complete 500 Activities
- [x] Complete 1,000 Activities

# Use Quill Premium
- [x] Start Trial 
- [x] View Standards Reports
- [x] View Concept Reports
- [x] Download CSV of Report
- [x] Activate Premium

**Comment by lopezabegaillyn** [comment]
Hi @petergault 

Do we have updates about this?
