### ISSUE TITLE
Connect Issue Tracker for Milestone 4

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2015]
- [x] https://github.com/empirical-org/Quill-Connect/issues/369 Modified Word Spelling error
- [x] https://github.com/empirical-org/Quill-Connect/issues/370 Joining Words
- [x] https://github.com/empirical-org/Quill-Connect/issues/371 Spacing Before Punc algo
- [x] https://github.com/empirical-org/Quill-Connect/issues/372 Move whitespace algo
- [x] https://github.com/empirical-org/Quill-Connect/issues/373 NaN in pop answers
- [x] https://github.com/empirical-org/Quill-Connect/issues/374 Punctuation in change objects.
