### ISSUE TITLE
Fire Segment Event for Each Checklist Item

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#2744]
# View Tutorials for Each Quill Tool
- [ ] View Quill Overview Tutorial 
- [ ] View Quill Diagnostic Tutorial
- [ ] View Quill Lessons Tutorial
- [ ] View Quill Connect Tutorial

# Assign Activity From Each Tool
- [x] Assign Quill Diagnostic Activity
- [x] Assign Quill Lessons Activity
- [x] Assign Quill Connect Activity
- [x] Assign Quill Proofreader Activity
- [x] Assign Quill Grammar Activity

# Complete Activities With Your Students
- [x] Complete 10 Activities 
- [x] Complete 100 Activities
- [x] Complete 250 Activities
- [x] Complete 500 Activities
- [x] Complete 1,000 Activities

# Use Quill Premium
- [x] Start Trial 
- [x] View Standards Reports
- [x] View Concept Reports
- [x] Download CSV of Report
- [x] Activate Premium
