### ISSUE TITLE
Great Big List of Technical Debt

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3019]
This is an issue for keeping track of all the technical debt we want to come back around to when we have a bit more bandwidth. Feel free to edit the issue and add your stuff under the appropriate header (or in the 'Triage' section).

---

**Upgrade Debt**
- [ ] Discuss using Webpacker w/ React for the Rails 5 upgrade? (It's _pretty_ nice.)
- [ ] Upgrade Rails to Rails 5
- [ ] Upgrade React to React 16
- [ ] Upgrade redis-namespace to v2

**Security Debt**
- [x] Install and configure the [Rack::Attack gem](https://github.com/kickstarter/rack-attack) (#3582)
- [x] Configure Brakeman to run on Travis (`bundle exec brakeman` in `.travis`) (#3345)
- [x] Install [Sqreen user monitoring](https://doc.sqreen.io/docs/ruby-agent-users-monitoring)
- [ ] Use [Git Secrets](https://github.com/awslabs/git-secrets)
- [x] [Audit S3 buckets](https://thenextweb.com/dd/2017/10/19/find-unprotected-amazon-s3-buckets-free-tool/)
- [ ] Get a happy green SSL padlock

**High Priority**
- [x] Move `generateNewCaUnit`, `parseUnits`, and `orderUnits` functions into a module, test them thoroughly, and replace the current implementations throughout the codebase with the module. (#3746)
- [x] stop having nil (and empty array) in classroom_activity.assigned_students_ids mean it's assigned to the whole freaking class. Add whole class boolean instead.

**Testing Debt**
- [x] CodeCov: integrate backend tests, improve configuration (#3346)
- [ ] Jest: write significantly better tests for classroom activity component and other components related to #3046.
- [ ] Jest: StudentProfile (Something wonky was happening with these in #2891, so I just skipped them for now to prevent that from being a blocker (the rest of the suite was passing at this point). These are a critical coverage point, so we should probably rewrite them from the ground up.)
- [ ] Jest: other skipped tests
- [ ] Use more specific error matchers in RSpec suite
- [ ] Fix pending tests in RSpec suite

**Triage**
- [ ] Clean up the `routes.rb` file (idea: make them follow the Rails conventions, and then share a JSON blob to the front end with those routes)
- [ ] `client/app/bundles/HelloWorld/components/lesson_planner/manage_units/manage_units.jsx` ajax methods should not update state without confirmation from the server that the intended behavior actually occurred
- [ ] Go through the site and move images to the CDN (in progress: @emilia-friedberg)
- [ ] Implement functionality to keep track of constants, as well as share them between the front end and the back end. (It may also be worth considering doing this for Rails routes.)
- [ ] Deprecate user roles: `temporary` and `user`
- [ ] Deprecate `clever_id` from `School` model
- [ ] Deprecate `activity_classification_id` from `ConceptResult` model
- [ ] Deprecate student role from ArchivedClassroomsManager
- [ ] Deprecate jQuery
- [ ] Deprecate 'active' column on users.
