### ISSUE TITLE
Passing data back to Google Classroom

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#3390]
### Questions
- Investigate how other apps do this. Khan and Newsela probably support this. Add screenshots if possible. 
- Can we display units or just individual activities?
- We probably need to do this on a per-student basis, not per classroom, as packs assigned to just half of the class will need to be shown correctly.
- How do we display lessons until they are launched
- If we post scores back, make sure that both the teachers and students can see it.
- Is this premium?
- Can we query the current state of students google classroom profile to prevent duplicates?

### Tasks
- [ ] Add hooks to classroom activities that check if the classroom is in google classroom, and update the data on Google Classroom if necessary.
- [ ] Add hooks to activity sessions
- [ ] Write copy for the posted messages.
