### ISSUE TITLE
Compliance checklist

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3461]
This issue enhances our FERPA compliance.

### Web Security
- [x] Protect better against brute force attacks. (#3582)
- [x] Create a canary in the coal mine for staff accounts (#3584)

### Operational Security
- [ ] Ensure team's devices have full disk encryption enabled
- [ ] Does every staff member have 2FA set up on Heroku? AWS? Firebase?

### Third party security
- [x] S3 bucket audit (https://thenextweb.com/dd/2017/10/19/find-unprotected-amazon-s3-buckets-free-tool/)

### Third party compliance
- [ ] Do any of our third party integrations add tracking code to the site that shouldn't be there? 

### ToS / Privacy Policy Modifications
- [x]  ToS needs an ‘updated at’ date
- [ ] “Disclose clearly and concisely with the school what types of student data are collected and what purposes you may use or share this information.” Build a nice table that shows all of this. Add it to the Privacy Policy page.
- [ ] On any sales-related page where we collect money, we should link to the policies.
- [ ] We should explicitly note that subdomains of quill.org are also governed by these policies.

### Other
See offline notes.
