### ISSUE TITLE
Reports Update Meta Issue

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3613]
- [x] Visual Overview: https://github.com/empirical-org/Empirical-Core/issues/3608 - Jared
- [x] Reports Landing: https://github.com/empirical-org/Empirical-Core/issues/3609
- [x] Activity Scores: https://github.com/empirical-org/Empirical-Core/issues/3574
- [x] Concepts Report: https://github.com/empirical-org/Empirical-Core/issues/3612 - Ryan
- [x] Standards Report: https://github.com/empirical-org/Empirical-Core/issues/3614 - Emilia
- [x] Data Export Report (previously List Overview): https://github.com/empirical-org/Empirical-Core/issues/3611 - Jared
- [x] Activity Analysis: #3637 - Jared
- [x] Activity Analysis (Activity Breakdown Page): #3637 - Ryan
- [x] Explore All Activities Page: https://github.com/empirical-org/Empirical-Core/issues/3610 - Ryan
- [x] Manage Classes Page: https://github.com/empirical-org/Empirical-Core/issues/3598 - Jared
- [x] audit item dropdowns to ensure none are broken - https://github.com/empirical-org/Empirical-Core/issues/3621 - Ryan
- [x] Selected Activities section of Manage Units page #3624 - Emilia
---

Add tests? 😇 
  
Follow-up Issues based on staging:
- [x] Visual Overview: #3644 - Emilia
- [x] Reports Landing: #3641 - Emilia
- [ ] Activity Scores: #3645 (waiting for it to be on staging)
- [x] Concepts Report: #3642 - Emilia
- [x] Standards Report: #3643 - Emilia
- [ ] Data Export Report (previously List Overview): (waiting for it to be on staging)
- [x] Explore All Activities: #3647 - Emilia
