### ISSUE TITLE
Audit Dependencies

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3619]
### Live footage of our dependencies:

![](https://media.giphy.com/media/l0IynvPneUpb7SnBe/giphy.gif)

---

### TODO:
- [ ] Remove unused gems
- [ ] Check each gem's version restriction (e.g. React on Rails is _way_ behind)
- [ ] Update gems
- [ ] Remove unused npm packages
- [ ] Check each npm package's version restriction
- [ ] Update npm packages
