### ISSUE TITLE
Activity Scores: Followup Issue

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3669]
Premium buttons:
- [x] no need for the underline on hover, can we instead just give it the orange fill, white text, and white star

Main Table Page:
- [x] the horizontal space next to the chevron is 25 px
- [x] headers left aligned with the content under them
- [x] clicking anywhere in the row send the teacher to the individual student report
- [x] when hover over a row, change the cursor of the mouse to the pointer
- [x] change color of the student name to #00c2a2

Student Page:

- [x] round edges for all the tables to 6px
- [x] the horizontal space between the tool square and the name of the activity is 15px
- [x] missing chevrons over the entire page
- [x] Download Report is 20px from the left 
- [x] hover over the activity name changes color to #00c2a2 and the whole row is clickable
- [x] clicking on each activity should send the teachers to the report or activity analysis of that activity.
- [x] Download Report button no need for the underline
- [x] Back to Activity Scores no need for underline, just change color to #00c2a2 with the chevron
