### ISSUE TITLE
Activity Scores New Issue with Routes

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3717]
Premium buttons in the subnav:
- [ ] no need for the underline on hover, can we instead just give it the orange fill, white text, and white star

Activity Score landing page: (https://www.quill.org/teachers/progress_reports/activities_scores_by_classroom)
- [ ] the horizontal space next to the chevron is 25 px
- [ ] headers left aligned with the content under them
- [ ] clicking anywhere in the row send the teacher to the individual student report
- [ ] when hovering over a row, change the cursor of the mouse to the pointer
- [ ] change color of the student name to #00c2a2

Activity Scores filtered by student page: (https://www.quill.org/teachers/progress_reports/student_overview?classroom_id=237663&student_id=2333748)
- [ ] round edges for all the tables to 6px
- [ ] the horizontal space between the tool square and the name of the activity is 15px
- [ ] when hovering over the activity, name changes color to #00c2a2 and the whole row is clickable
- [ ] clicking on each row should send the teachers to the report or activity analysis of that activity.
- [ ] Back to Activity Scores no need for underline, just change color to #00c2a2 with the chevron

**Comment by emilia-friedberg** [comment]
A lot of these should be handled by https://github.com/empirical-org/Empirical-Core/pull/3675. Not sure why those changes aren't live. @ddmck ?

**Comment by emilia-friedberg** [comment]
@amr-thameen These changes should be live now, can you audit and see if we can close this issue?
