### ISSUE TITLE
Affiliates v1, Part One

### ISSUE THREAD

**Issue by jaredsilver** [empirical-org/Empirical-Core#3733]
# Part One
### Initial Setup
- [x] Install [Rack Affiliates](https://github.com/alexlevin/rack-affiliates) gem
- [x] Determine a strategy for generating unique identifiers for the affiliate ID
- [x] Create table for associating affiliate IDs to users (would this be better just as an optional field on User?)
- [x] Write a rake task to automatically generate affiliate IDs in the form "firstname-lastname-id"
- [x] Create a callback for teachers that generates a unique affiliate ID on create
- [x] Create a table for associating new users with their referrers
- [x] Configure Rack Affiliates gem
- [x] Amend account creation process to create a referral association

### Tests
- [x] Add tests for new models
- [x] Add tests for referral codes in the account creation process
- [x] Add tests for methods introduced onto old models
