### ISSUE TITLE
on homepage, color of buttons on hover seems off

### ISSUE THREAD

**Issue by emilia-friedberg** [empirical-org/Empirical-Core#4026]
<img width="889" alt="screen shot 2018-03-20 at 5 13 12 pm" src="https://user-images.githubusercontent.com/18669014/37683169-0e8f3fc8-2c62-11e8-95e0-9bdfd4881400.png">
<img width="559" alt="screen shot 2018-03-20 at 5 13 19 pm" src="https://user-images.githubusercontent.com/18669014/37683170-0e9bac36-2c62-11e8-9794-ce4636ff9950.png">
<img width="605" alt="screen shot 2018-03-20 at 5 13 33 pm" src="https://user-images.githubusercontent.com/18669014/37683171-0ea56fc8-2c62-11e8-969f-ca34828e856f.png">

**Comment by amr-thameen** [comment]
- [ ] Sign up in the nav bar -> fill: #FFFFFF ; text: #00C2A2
- [ ] Sign up under H1 -> fill: #00DFB1 ; text: #FFFFFF
- [ ] Learn More -> fill: #FFFFFF; text: background color
- [ ] Try A Sample Activity: text: #FFFFFF ; connect: #F9B95C; diagnostic: #FF6473; grammar: #C96CF0; proofreader: #6CB3ED; lessons: #E358AB
